title: My Deal Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogging about the best deals and strategies.
baseurl: "/github-pages-with-jekyll"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
plugins:
  - jekyll-feed

collections:
  deals:
    output: true
    permalink: /deals/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "amazon-post"
  - scope:
      path: ""
      type: "deals"
    values:
      layout: "deal"
